# FOSRest Configuration
fos_rest:
    body_listener: true
    body_converter:
            enabled: true
    format_listener:
        rules:
            - { path: '^/api/v1', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/api/doc', priorities: ['html'], fallback_format: html, prefer_extension: true }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    routing_loader:
            default_format: json