imports:
    - { resource: parameters.yml }
    - { resource: log/monolog.yml }
    - { resource: security.yml }
    - { resource: jwt.yml }
    - { resource: services.yml }
    - { resource: doctrine/doctrine.yml }
    - { resource: framework/framework.yml }
    - { resource: swiftmailer/swiftmailer.yml }
    - { resource: nelmio/nelmio_api_doc.yml }
    - { resource: nelmio/nelmio_cors.yml }
    - { resource: fos/fos_rest.yml }
    - { resource: "@CmsBundle/Resources/config/services.yml" }
    - { resource: "@HomepagePromoPageBundle/Resources/config/services.yml" }
    - { resource: "@GalleryBundle/Resources/config/services.yml" }
    - { resource: "@HomepageSliderBundle/Resources/config/services.yml" }
    - { resource: "@ReferencesBundle/Resources/config/services.yml" }
    - { resource: "@CalculatorBundle/Resources/config/services.yml" }
    - { resource: "@EcommerceBundle/Resources/config/services.yml" }
    - { resource: "@AttachmentBundle/Resources/config/services.yml" }
    - { resource: "@ContentBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
sensio_framework_extra:
    request: { converters: true }