<?php

namespace Components\ReferencesBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentReferenceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentReferenceItemRepository extends AbstractRepository
{
}
