<?php

namespace Components\HomepageSliderBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentSliderMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentSliderMetaRepository extends AbstractRepository
{
}
