nelmio_api_doc:
    routes:
        path_patterns: # an array of regexps
            - ^/api
    documentation:
        info:
            title: Core PromoImage
            description: This is an awesome app!
            version: 1.0.0