<?php

namespace Components\HomepagePromoPageBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentHomepagePromopageMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentHomepagePromopageMetaRepository extends AbstractRepository
{
    
}
