<?php

namespace Components\CalculatorBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentCalculatorParamItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentCalculatorParamItemRepository extends AbstractRepository
{
}
