<?php

namespace Components\CalculatorBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentCalculatorParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentCalculatorParameterRepository extends AbstractRepository
{
}
