<?php

namespace CmsBundle\Repository;

/**
 * ClientAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAppRepository extends AbstractRepository
{
}
