<?php

namespace CmsBundle\Repository;

/**
 * ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsListRepository extends AbstractRepository
{
}
