<?php

namespace CmsBundle\Repository;

/**
 * CmsListTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsListTypeRepository extends AbstractRepository
{
}
