<?php

namespace CmsBundle\Repository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentRegisterRepository extends AbstractRepository
{

    public function getOneByName($name)
    {
       return $this->findOneBy(["componentName" => $name]);
    }
}
