<?php

namespace CmsBundle\Repository;

/**
 * StructureILevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureLevelRepository extends AbstractRepository
{
    /**
     * @return mixed
     */
    public function getLevelsIds()
    {
       $levels = $this->findAll();

        foreach ($levels as $level){

            $arr[$level->getTitle()] = $level->getId();
        }

        return $arr;
    }

    /**
     * @return mixed
     */
    public function getLevels()
    {
        $levels = $this->findAll();

        foreach ($levels as $level){

            $arr[$level->getTitle()] = $level;
        }

        return $arr;
    }
}
