<?php

namespace CmsBundle\Repository;
use CmsBundle\Entity\ComponentRegister;
use CmsBundle\Entity\StructureComponent;
use CmsBundle\Entity\StructureItem;

/**
 * StructureComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureComponentRepository extends AbstractRepository
{
    /**
     * Merging component instance with structure item
     * @param ComponentRegister $register
     * @param StructureItem $structureItem
     * @return StructureComponent
     */
    public function addComponentToStructureItem(ComponentRegister $register, StructureItem $structureItem)
    {
        $structureComponent = new StructureComponent();
        $structureComponent->setStructureItem($structureItem);
        $structureComponent->setComponentRegister($register);
        
        return $this->save($structureComponent);
    }
}
