<?php

namespace CmsBundle\Repository;

/**
 * ClientTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebUserTokenRepository extends AbstractRepository
{
}
