<?php

namespace Components\GalleryBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentGalleryAlbumItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentGalleryAlbumItemRepository extends AbstractRepository
{
}
