<?php

namespace Components\AttachmentBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentAttachmentStoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentAttachmentStoreRepository extends AbstractRepository
{
}
