<?php

namespace Components\AttachmentBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentAttachmentItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentAttachmentItemRepository extends AbstractRepository
{
}
