<?php

namespace Modules\EcommerceBundle\Repository;

/**
 * ProductImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcommerceProductImageRepository extends \Doctrine\ORM\EntityRepository
{
}
