<?php

namespace Modules\EcommerceBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcommerceInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
