<?php

namespace Modules\EcommerceBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcommerceCategoryRepository extends AbstractRepository
{
}
