<?php

namespace Modules\EcommerceBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcommerceProductRepository extends \Doctrine\ORM\EntityRepository
{
}
