<?php

namespace Modules\EcommerceBundle\Repository;

/**
 * AttributesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcommerceAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
