<?php

namespace Components\ContentBundle\Repository;
use CmsBundle\Repository\AbstractRepository;

/**
 * ComponentContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentContentRepository extends AbstractRepository
{
}
